apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2020-01-01T01:26:15Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-b
  name: pvc-b2727028-2c35-11ea-8c88-42010a8e0044
  resourceVersion: "962"
  selfLink: /api/v1/persistentvolumes/pvc-b2727028-2c35-11ea-8c88-42010a8e0044
  uid: b4083347-2c35-11ea-8c88-42010a8e0044
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-1-jenkins-pvc-jenkins-1-jenkins-0
    namespace: default
    resourceVersion: "930"
    uid: b2727028-2c35-11ea-8c88-42010a8e0044
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-cluster-1-25a7e609-pvc-b2727028-2c35-11ea-8c88-42010a8e0044
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound