apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-01-01T01:26:12Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/name: jenkins-1
  name: jenkins-1-jenkins-pvc-jenkins-1-jenkins-0
  namespace: default
  resourceVersion: "964"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/jenkins-1-jenkins-pvc-jenkins-1-jenkins-0
  uid: b2727028-2c35-11ea-8c88-42010a8e0044
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-b2727028-2c35-11ea-8c88-42010a8e0044
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound